### ISSUE TITLE
erase_flash option not working

### ISSUE THREAD

**Issue by jmai444** [themadinventor/esptool#141]
erase_flash is not working for me, it always returns to the prompt immediately after printing a couple of messages:

```
~$ sudo /usr/local/bin/esptool.py --port /dev/ttyUSB0 erase_flash
esptool.py v1.1
Connecting...
Erasing flash (this may take a while)...
~$
```
The write_flash option seems to work, but I've occasionally had trouble getting a good flash.

**Comment by projectgus** [comment]
Thanks for providing a detailed report, @jmai444 .

esptool v1.1 doesn't wait for flash erase completion, so there's no way to know if the erase operation is done. If you install v1.2.1 (the current stable release) then it has an updated erase_flash routine that waits until completion before exiting.

A couple of things to keep in mind:
* The erase_flash operation can take a long time (I have some flash chips where it's upwards of 25 seconds.)
* You don't usually need to erase_flash before write_flash, esptool.py will erase each sector before it writes it.
