### ISSUE TITLE
Some fixes from nodemcu

### ISSUE THREAD

**Issue by sej7278** [themadinventor/esptool#15]
Could you have a look at https://github.com/nodemcu/nodemcu-firmware/blob/2709258c44b4fa2397df736b12b9c2ef86dc4d89/tools/esptool.py please, and see if you can/should merge in the fixes there?

basically its setting permissions to 755 so it can be executed on unix and removing the version from the shebang from me as discussed earlier.

also from @nodemcu it seems like a fix for the windows hanging issue - basically uses xt-objcopy instead of xtensa-lx106-elf-objcopy and  xt-nm instead of xtensa-lx106-elf-nm

i can't really do a direct PR as its across two different projects, nodemcu should probably use your repo as a submodule i guess, or leave it to the user to install esptool.py in the $PATH somewhere.

**Comment by themadinventor** [comment]
Fixed by 285ec621ff94c47d1cffa241a09902f35a9c0baf (reverting shebang line) and e20cc5e8c61dcd94b4ea0b331761632957c0c1fc (support for xt toolchain). esptool.py has always been executable in this repo ;)
