### ISSUE TITLE
Dependency on pyserial not documented

### ISSUE THREAD

**Issue by riban-bw** [themadinventor/esptool#17]
Having downloaded esptool, I found there was a dependency on pyserial. This is not documented and I needed to google for a while to find an answer. I am using cygwin and the solution for me was:

```
easy_install -U pyserial
```
It would be advantageous for this dependency (and tips on satisfying it) were documented in the README or similar location.

**Comment by themadinventor** [comment]
(Hopefully) fixed by ￼7468a170290cd56a592a6f408f9d926447d07773 :)
