### ISSUE TITLE
How to specify serial port in cygwin

### ISSUE THREAD

**Issue by riban-bw** [themadinventor/esptool#18]
I am using esptool.py within cygwin. It took a bit of googling to figure out how to specify a valid serial port. The answer is:

>esptool.py --port /dev/ttySx

where x is the Windows com port number minus one, e.g. to use COM5 the command would look like:

>esptool.py --port /dev/ttyS4

May I request this information be added to the documentation?

**Comment by sash13** [comment]
Try:
> esptool.py --port COM1

When "1" it's your number of port in windows device tree.

**Comment by themadinventor** [comment]
Fixed by
939712ae5511eaae8b8021d68376f71a464c723e

Thanks!
