### ISSUE TITLE
Support "elf2image --version=2" or similar (was: missing support for "boot mode 2")

### ISSUE THREAD

**Issue by tve** [themadinventor/esptool#39]
Is it correct that esptool doesn't support elf2image with "boot mode 2", which is what the newer boot loaders support (boot_v1.2+) and is required to support OTA flashing? Is support planned?

**Comment by projectgus** [comment]
You're correct that this boot mode (that also uses a binary bootloader image in the flash, or an open source bootloader like rboot) is not supported yet.

I'm going to mark this as an enhancement request and keep it open. PRs welcome!
