### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by amalashin** [themadinventor/esptool#57]
When flashing via esptool.py the device stucks in boot(3,0) and won't start. When flashing the same firmware via flash_download_tool everything works fine. How to troubleshoot this issue?

**Comment by kanflo** [comment]
You might have run into this bug:
https://github.com/themadinventor/esptool/issues/33

Try flashing the binaries in reverse order:
https://github.com/kanflo/esp-open-rtos/commit/d4873379a927eb28692a03509fad74d5ce4fe5f6

**Comment by amalashin** [comment]
@kanflo Yep, I faced exactly with this bug! Thank you very much for help. Files order switch resolved my problems.

**Comment by projectgus** [comment]
A fix for this should now be merged via PR #53.
