### ISSUE TITLE
Publish to PyPI.

### ISSUE THREAD

**Issue by skorokithakis** [themadinventor/esptool#63]
Can you do a `python setup.py sdist upload` so esptool gets published to PyPI? Then we'd be able to install it with just a `pip install esptool`.

**Comment by projectgus** [comment]
This sounds like a great idea.

I have never uploaded anything to PyPI before. Are you in a position to give any advice about whether esptool is ready for submission in its current state, or should other checks be done?


Angus

**Comment by pfalcon** [comment]
What about this for example: https://github.com/SuperHouse/esp-open-rtos/blob/master/lib/symbols_norename.txt#L1 ?

**Comment by projectgus** [comment]
> What about this for example: https://github.com/SuperHouse/esp-open-rtos/blob/master/lib/symbols_norename.txt#L1 ?

Hi @pfalcon,

Sorry, did you mean to leave this comment somewhere else? It's not clear to me how it relates to PyPI submission.

However, thanks for pointing that line in esp-open-rtos out. esptool.py no longer hardcodes the entry point name, as of some months ago it's loaded from the ELF file. In esp-open-rtos that `symbols_norename.txt` file is also no longer used and [should have been removed](https://github.com/SuperHouse/esp-open-rtos/commit/51c752dbcb754e77037b89f066b53b157b361991), all the symbols it lists are found in either our own source or newlib.

**Comment by pfalcon** [comment]
Nope, I meant to leave it here - I believed that issue was fixed, but as I was found to mix up things, I'd let you to confirm it (before publishing to pypi without that patch possibly merged).

> should have been removed

Cool, one issue confirmed fixed, another is fixed. ;-)

**Comment by skorokithakis** [comment]
What I would change before submitting to PyPI would be to make the script be called `esptool` after installation, rather than `esptool.py`, and to improve the documentation a bit. As a complete newbie to using it, I'm not very clear on how to use it. Then again, that might be more because I don't really know what it does or how, rather than a failure in the documentation.

**Comment by projectgus** [comment]
Good suggestions, thanks @skorokithakis.

> Then again, that might be more because I don't really know what it does or how, rather than a failure in the documentation.

I think that's a failure in documentation, in either case. :)

**Comment by skorokithakis** [comment]
Haha, possibly, but it may be out of scope for esptool.

**Comment by pfalcon** [comment]
> would be to make the script be called esptool after installation, rather than esptool.py

Keep in mind that there's another "esptool". I believe it's not even maintained by the original author, but it was picked up by folks who like to ship binaries in peoples' faces. Then more community-concious of them call it "esptool-ck", but I'm not sure if everyone does. And then the best thing this project can do keep people from confusion is to continue being called esptool.py .

**Comment by skorokithakis** [comment]
Sure, that's up to you. All I have is this esptool, but if you guys think that a collision has a reasonable chance of occurring, `esptool.py` is fine.
