### ISSUE TITLE
I want to download ESP8266 WiFi bin file through the C language program by uart。

### ISSUE THREAD

**Issue by WantDoIt** [themadinventor/esptool#72]
Hi~ 
      I want to download ESP8266 WiFi bin file through the C language program by uart。
However，I have no document about ESP8266 Bootloader. I don't how to set up a communication with  
ESP8266 Boot Mode.  If different types of flash，if I should send flash driver to ESP8266 Boot before downloading ESP8266 WiFi bin file ？Where could I get the datasheet of A serial port communication protocol ？
     Thank you !!!

**Comment by projectgus** [comment]
Hi,

The serial port bootloader on the ESP8266 is flashed into the ROM. It's not sent to the device by the upload tool.

The communication protocol is pretty much undocumented. All that we know is from reverse engineering the binary-only upload tool supplied by Espressif. There's some information here: https://github.com/themadinventor/esptool#protocol

... or you can read the esptool.py source code to see how it behaves.

I'm going to close this Issue now as it doesn't seem to be an ongoing problem with esptool.py.
