### ISSUE TITLE
Document the SPI flash mode parameters (in README.md)

### ISSUE THREAD

**Issue by marcelstoer** [themadinventor/esptool#84]
As per https://github.com/themadinventor/esptool/issues/68#issuecomment-167269472 and http://stackoverflow.com/a/35260240/131929 I think it's high time the available SPI flash mode parameters get properly documented. It probably also makes sense to provide a few samples for commonly used ESP modules (i.e. devkit v1, v2, WeMos D1 mini, etc.).

**Comment by projectgus** [comment]
Absolutely, go for it!

**Comment by marcelstoer** [comment]
> go for it!

Me? I don't know all those parameters (except for the 3 I dug up elsewhere).

**Comment by marcelstoer** [comment]
Thanks. Is there a reason you didn't document the short forms (i.e. `-fm -fs -ff`)?

**Comment by projectgus** [comment]
I just didn't think of it. Pull requests welcome! :)

**Comment by marcelstoer** [comment]
Will do.
