### ISSUE TITLE
write_flash --verify doesn't exit bootloader after verifying

### ISSUE THREAD

**Issue by projectgus** [themadinventor/esptool#99]
Reported by @pfalcon as a comment to PR #89:
> when using write_flash --verify with latest master, device remains in bootloader mode, and I need to execute esptool.py run manually.

**Comment by pfalcon** [comment]
This appears to be fixed by https://github.com/themadinventor/esptool/commit/0d6556136338387f2e0790407d7c792c452ce2b1 .

**Comment by projectgus** [comment]
Agreed, thanks. Closing.
